ContractPortal.sln.DotSettings
documents/technical-guide.md
src/BlazorApp/Pages/Error.cshtml.cs

3 example story 1

---

src/Client/Pages/Admin.razor
src/Client/Shared/NavMenu.razor

Add an empty admin page.
Closes #29

Add admin page

---

src/Client/Pages/AboutUs.razor
src/Client/Shared/NavMenu.razor

Added about us page describing the company and using one of their photos from the current website 
Closes #12

12 about us page

---

src/Client/Pages/Admin.razor
src/Client/Pages/ContractList.razor
src/Client/Pages/ContractListItem.razor
tests/Client.Tests/Pages/AdminPageTests.cs
tests/Client.Tests/Pages/ContractListItemTests.cs
tests/Client.Tests/Pages/ContractsPageTests.cs
tests/Client.Tests/Pages/UITestFixture.cs

Adds contract list to the admin page. 
Closes #24

24 show contracts in admin panel

---

src/Client/Pages/Dashboard.razor
src/Client/Shared/NavMenu.razor

Added a dashboard page and put a link to it into the navmenu.
Closes #44

44 create dashboard page

---

src/Client/Pages/Admin/ContractForm.razor
src/Client/Pages/ContractsPage.razor
src/Domain/Contracts/Contract.cs
src/Infrastructure/Contracts/FakeContractRepository.cs
tests/Presentation.Tests/Client/Pages/ContractsPageTests.cs

Co-authored-by: Ella Sibbmark <ella@sibbmark.se>
Additional fields to Contract have been added for additional images and documents. Fields for specifying supplier name and info has also been added.

Add additional fields to Contract

---

src/Client/Pages/AboutUs.razor
src/Client/Pages/Admin/AdminPage.razor
src/Client/Pages/Dashboard.razor
src/Client/wwwroot/css/app.css

Changes the style sheet to create a uniform styling of the website.
Closes #43

43 implement a global style sheet

---

src/Client/Pages/Admin/ContractForm.razor
src/Client/Pages/Contracts/ContractDetails.razor
src/Domain/Contracts/Contract.cs
tests/Presentation.Tests/Client/Pages/Contracts/ContractDetailsTests.cs

Add a FAQ section to the detailed contract view, which is only shown if FAQ is not an empty string. An entry field has been added to the admin page for FAQ.
With FAQ:
With no FAQ:
Closes #56

56 View contract FAQ-section

---

src/Client/Pages/Contracts/ContractsPage.razor
src/Client/Pages/Contracts/SearchBar.razor

Adds a search bar to the top of the contracts page that currently only takes input and prints it. It does not perform any contract filtering as that is being implemented in #67.
Closes #59

59 search bar

---

src/Application/Contracts/ContractService.cs
src/Application/Contracts/IContractService.cs
src/Client/Pages/Contracts/ContractsPage.razor
src/Client/Shared/FetchData.razor
src/Server/Controllers/ContractsController.cs
tests/Application.Tests/Contracts/ContractServiceTests.cs
tests/Presentation.Tests/Server/Controllers/ContractsControllerTests.cs

Makes contracts page only show contracts that are returned by the backend as a result of a search query. When no query is input, all contracts are shown.
Closes #67

67 search result filtering

---

.gitignore
.idea/.idea.ContractPortal/.idea/misc.xml
src/Application/Contracts/ContractService.cs
src/Application/Search/Modules/TagSearch.cs
src/Domain/Contracts/Contract.cs
src/Infrastructure/Contracts/FakeContractRepository.cs
tests/Application.Tests/Search/Modules/TagSearchModuleTests.cs

Adds tag searching to the search engine used by the contracts search box. You can now search for predefined tags and have contracts containing those tags show up.
Closes #66

66 keyword search

---

src/Infrastructure/Migrations/20220505152704_AddPassword.Designer.cs
src/Infrastructure/Migrations/20220505152704_AddPassword.cs

Fixes a mismatch between the database migrations and the C# classes.

hotfix password column

---

src/Client/Pages/Contracts/ContractCard.razor
src/Client/Pages/Contracts/ContractCard.razor.css
src/Client/Pages/Contracts/ContractsPage.razor
src/Client/Pages/Contracts/FavoriteButton.razor
src/Client/Pages/Contracts/FavoriteButton.razor.css

Contract cards have a unifrom size. The amount of cards on a row change depending on the screen size, and if the title is too long then ellipsis are used.
Closes #128 
Closes #126

128 remastering contract cards

---

src/Client/Pages/Contracts/ContractCard.razor
src/Client/Pages/Contracts/ContractCard.razor.css
src/Client/Pages/Contracts/ContractsPage.razor
src/Client/Pages/Contracts/ContractsPage.razor.css

The maximum number of cards is now 4 and minimum 1. The size and styling of the cards have been changed, please check on your own laptop if you think they are the right size. 
Closes #159

159 resize contract cards

---

.github/workflows/dotnet.yml
src/Client/App.razor
src/Client/Client.csproj
src/Client/Pages/AboutUs.razor
src/Client/Pages/Admin/AdminPage.razor
src/Client/Pages/Contracts/ContractsPage.razor
src/Client/Pages/Dashboard/DashboardPage.razor
src/Client/Pages/WelcomePage.razor
src/Client/Program.cs
src/Client/_Imports.razor
src/Client/wwwroot/index.html
tests/Client.Tests/Client.Tests.csproj

Adds Google Analytics integration to the website, enabling basic user activity tracking.
Closes #98

98 adding analytics tools

---

src/Client/Pages/AboutUs.razor
src/Client/Pages/Admin/AdminPage.razor
src/Client/Pages/Contracts/ContractsPage.razor
src/Client/Pages/Dashboard/DashboardPage.razor
src/Client/Shared/Login/LoginModal.razor

A loading indicator is now shown when logging in.
Closes #151

151 login loading indicator

---

README.md

Changes the connection string in the readme

Change string from master to ProdigoPortal

---

src/Client/Services/Authentication/SessionManagerService.cs
src/Client/Shared/Login/LoginModal.razor
tests/Client.Tests/UITestFixture.cs

Tracks the beginning of every new user session.
Closes #121

121 track login

---

src/Client/Pages/Contracts/ContractDetails.razor.css

Co-authored-by: Ella Sibbmark <ella@sibbmark.se>
Fixes so that text doesn't go outside the modal. Also did some minor styling to center the title and make it look a bit more neat. 
Closes #172

Add word wrapping

---

src/Application/Users/UserService.cs
tests/Application.Tests/Users/UserServiceTests.cs

Ensure password is encrypted on user update

---

src/Client/Pages/Contracts/ContractsPage.razor
tests/Client.Tests/UITestFixture.cs

Contract search queries are now tracked in Google Analytics.
Closes #122

122 track search queries

---

src/Client/Pages/Contracts/ContractDetails.razor
tests/Client.Tests/UITestFixture.cs

Tracks when a user opens the details view, either by clicking on a contract or navigating through a link.
Closes #176

176 track contracts

---

src/Client/Pages/Admin/NotificationComponents/NotificationTableRow.razor
src/Client/Pages/Dashboard/DateTimeOffsetFormattingExtensions.cs
src/Domain/StatusUpdates/StatusUpdate.cs
src/Infrastructure/Migrations/20220522062706_ConvertTimestampToDateTimeOffset.Designer.cs
src/Infrastructure/Migrations/20220522062706_ConvertTimestampToDateTimeOffset.cs

Bugfix 181 incorrect time zone in status updates

---

src/Client/Pages/Admin/ContractComponents/ContractForm.razor

Makes all contract file uploads optional.

Do not try to upload files if not provided
